language: python
python:
  - '3.6'

branches:
  only:
    - sources

env:
  global:
    - secure: TSmK2m67mNAzfma+b9NVz4Rp11Vp0SdTE0E3wDTTbuLL6gRkejYovE5uqzzNuMj8nKuj3M9ucOUBknFVj+P8m778O681cjhCZqCqHaMaziasM1ehbxyoQe4wErc5zN2qqaCkCzFsubNVoK5aqdo4YJuD7wn5hsOR+wDqfCMHcs/l6jk8DeUW8xn7ZgBoyx9zDoIvemUZW/Mw42HM5Yw/eAagNWcByRHia0fsSAvUkPvMTp8/IOZRAGj2dZlISrbvsE7nWuWMJEVhpOSmqcCoYhpbAgN+Utat6AI8Fopmusm+/JKv4gCjvibJnz6RLXg3IMYWr1MTCkIiD3HwfMnQxvFr1se6s+6y4d0h19C2b2BuXTG6NY/74AOe07wmFVcXlR63CahFRK2O/KUdeS+fB7gQlE/3hU58aX/cw0uGiAIZKOaEbV2fQwkTH1EyECkVG1esogxV5XculCjNJAeYtDgflmPHUFP5uUer9kucO/e7MhoAwQW+amoWjZtyJrD18avd7PWW9WYQFYmJhw2H7Amy8dceGcQn7Nvcmsu4zeQoapGWzwkj03xqh4WgFcI70B8M9lKfo6HoMfoV75C+I0EFf/Cj2QPPYJISnvgI28aA5OeKE2UY1tNFnyWHHPLnInCNVPzcbleTRpXn2dmh0t1cuuBOrBO6rNlwp4B7arQ=

before_install:
  - pip install pelican markdown ipython notebook ghp-import

install: true

script:
  - make publish-to-github-force
